"""
llm/base.py

LLMBackend abstract base class defining the unified interface all backends must implement.
Agent Core depends only on this abstraction and never imports any concrete SDK.

Also contains:
- LLMMessage / LLMResponse / LLMToolSchema data classes (unified format across backends)
- MockBackend (test-only; returns scripted actions without consuming any API calls)
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

from agent.task import Action, ActionType, ToolCall


# ---------------------------------------------------------------------------
# Unified data format across backends
# ---------------------------------------------------------------------------

@dataclass
class LLMMessage:
    """
    A single message sent to the LLM.
    role: "system" | "user" | "assistant"
    content is plain text; tool_call_id is only used when role=="tool" (OpenAI format).
    """
    role: str
    content: str
    tool_call_id: str | None = None     # required when returning tool results in OpenAI format


@dataclass
class LLMToolSchema:
    """
    Schema describing one available tool to the LLM.
    Generated by ToolRegistry.get_schemas() and injected into the LLM's tools parameter.
    """
    name: str
    description: str
    parameters: dict[str, Any]          # JSON Schema format


@dataclass
class LLMResponse:
    """
    Unified response format returned by all backends.
    Each backend is responsible for parsing its API's raw response into this structure.
    """
    action: Action                      # parsed Action, used directly by core.py
    raw_content: str                    # raw text output from the LLM, for debugging
    input_tokens: int = 0
    output_tokens: int = 0

    @property
    def total_tokens(self) -> int:
        return self.input_tokens + self.output_tokens


# ---------------------------------------------------------------------------
# Abstract base class
# ---------------------------------------------------------------------------

class LLMBackend(ABC):
    """
    Interface that all LLM backends must implement.

    Subclasses implement complete(), which is responsible for:
    1. Converting the LLMMessage list into each provider's request format
    2. Sending the request
    3. Parsing the response into an LLMResponse (including the Action)
    """

    @abstractmethod
    def complete(
        self,
        messages: list[LLMMessage],
        tools: list[LLMToolSchema],
    ) -> LLMResponse:
        """
        Call the LLM and return a parsed response.

        Args:
            messages: full conversation history, including the system prompt
            tools:    list of tool schemas available to the model

        Returns:
            LLMResponse with a fully parsed action ready for core.py
        """
        ...

    @property
    @abstractmethod
    def model_name(self) -> str:
        """Return the name of the current model, used for logging and statistics."""
        ...

    @property
    def supports_function_calling(self) -> bool:
        """
        Whether this backend supports function calling.
        Default True; models that don't (e.g. DeepSeek R1) override to return False,
        and core.py switches to text-parsing path.
        """
        return True

    def stream(
        self,
        messages: "list[LLMMessage]",
        tools: "list[LLMToolSchema]",
        on_text: "StreamCallback | None" = None,
        on_thought: "StreamCallback | None" = None,
    ) -> "LLMResponse":
        """
        Streaming LLM call. Falls back to complete() by default.
        on_text:    callback for each text chunk of the final answer
        on_thought: callback for each chunk of the reasoning process (reasoning models only)
        """
        response = self.complete(messages, tools)
        if on_text and response.raw_content:
            on_text(response.raw_content)
        return response


# ---------------------------------------------------------------------------
# MockBackend — test-only
# ---------------------------------------------------------------------------

class MockBackend(LLMBackend):
    """
    Test-only backend that returns scripted Actions in order.

    Usage:
        script = [
            Action(ActionType.TOOL_CALL, "run tests", ToolCall("shell", {"cmd": "pytest"})),
            Action(ActionType.FINISH, "all tests pass", message="Done"),
        ]
        backend = MockBackend(script)
        # Each complete() call returns the next Action from the script.
        # After the script is exhausted, automatically returns GIVE_UP.

    Benefits:
    - No API consumption; tests are fast and deterministic
    - Precise control over which code paths the agent takes
    - Can simulate consecutive identical actions to trigger loop detection
    """

    def __init__(
        self,
        script: list[Action],
        input_tokens: int = 100,
        output_tokens: int = 50,
    ) -> None:
        self._script = script
        self._index = 0
        self._input_tokens = input_tokens
        self._output_tokens = output_tokens
        # Record all complete() calls for test assertions
        self.call_count = 0
        self.received_messages: list[list[LLMMessage]] = []

    @property
    def model_name(self) -> str:
        return "mock-model"

    def complete(
        self,
        messages: list[LLMMessage],
        tools: list[LLMToolSchema],
    ) -> LLMResponse:
        self.call_count += 1
        self.received_messages.append(messages)

        if self._index < len(self._script):
            action = self._script[self._index]
            self._index += 1
        else:
            # Script exhausted; return GIVE_UP to prevent an infinite loop in core.py
            action = Action(
                action_type=ActionType.GIVE_UP,
                thought="MockBackend script exhausted.",
                message="No more scripted actions.",
            )

        return LLMResponse(
            action=action,
            raw_content=f"[mock] {action!r}",
            input_tokens=self._input_tokens,
            output_tokens=self._output_tokens,
        )

    def reset(self) -> None:
        """Reset the script pointer to reuse the same backend across multiple tests."""
        self._index = 0
        self.call_count = 0
        self.received_messages.clear()


# ---------------------------------------------------------------------------
# Streaming support
# ---------------------------------------------------------------------------

from typing import Generator, Callable


@dataclass
class StreamChunk:
    """
    A single chunk in a streaming response.
    text_delta:     the new text fragment added by this chunk (thought portion)
    is_done:        True when this is the last chunk
    final_response: contains the complete LLMResponse when is_done=True
    """
    text_delta: str = ""
    is_done: bool = False
    final_response: "LLMResponse | None" = None


# Callable type: receives text_delta for real-time printing
StreamCallback = Callable[[str], None]


class StreamingMixin:
    """
    Mixin that adds streaming capability to LLMBackend subclasses.
    Subclasses implement stream(); complete() can reuse it.
    """

    def stream(
        self,
        messages: "list[LLMMessage]",
        tools: "list[LLMToolSchema]",
        on_text: StreamCallback | None = None,
    ) -> "LLMResponse":
        """
        Streaming LLM call.

        Args:
            messages:  full conversation history
            tools:     list of tool schemas
            on_text:   callback invoked for each text chunk for real-time thought printing

        Returns:
            Complete LLMResponse (returned only after the stream ends; same format as complete())

        Default implementation: calls complete() directly (non-streaming fallback).
        Backends that support streaming override this method.
        """
        response = self.complete(messages, tools)  # type: ignore[attr-defined]
        # Non-streaming fallback: emit raw_content as a single output event
        if on_text and response.raw_content:
            on_text(response.raw_content)
        return response
